#==============================SONATA-Configuration-Input YAML=============================
#This file contains the input information for the structural design of the rotorblade crosssection
#Author: Tobias Pflumm
#Date:	03/19/2018
#===============================SETUP===================================				 
Setup:
    input_type: 4						   #0) Airfoil from UIUC Database; 1) Geometry from .dat file; 2)2d .step 3)3D .step + radial station of crosssection 	4) gen, 3D-Blade f. twist,taper,airfoils,1/4-line	[int] DEFAULT=0	
    datasource: jobs/VariSpeed/uh60a_data_blade/uh60a_blade_zerotwist  #0)	naca23012					1) AREA_R250.dat			2)AREA_R230.stp	 			3)AREA_Blatt_L.stp	 4)folder of data 						                    [str] DEFAULT=NONE
    material_db: examples/mat_db.yml	   #Path and filename of the Material Database						#True or False for Balance Weight			                                                            [bool] DEFAULT=FALSE
    radial_station: 2500					#Radial station of crosssection. Only necessary for input type 3. [float]	Default=NONE
    Theta: 0							#To place the Origin of the SONATA Coordinates at the intersection of the by Theta rotated xaxis. [float] DEFAULT = 0
    scale_factor: 1						#use as reference scale factor				[float] 		DEFAULT=1
    BalanceWeight: True		
    mesh_resolution: 260				#Scales approximately to the number of points on Segment0

#=======WEBS=======			
Webs:
    Web 1:								#WebName									[int]	
        Pos1: 0.44						
        Pos2: 0.56
	
    Web 2:
        Pos1: 0.3
        Pos2: 0.7

#=======SEGMENTS==	
Segments:
    Segment 0:							#Web ID 									[int]	
        CoreMaterial: 3
        Layup: 
            #-[Start[-],End[-],thickness[mm],Orientation [deg],MatID[int],'name'[str]]	
            - [0.44, 0.56, 0.82,   0, 7, 'Erosion_Strip']
            - [0.00, 1.00, 0.25,  0, 8, 'Overwrap_Ply_1']
            - [0.0, 1.00, 0.25,   45, 8, 'Overwrap_Ply_2']
            - [0.0, 1.00, 0.25,   45, 8, 'Overwrap_Ply_3']	
            - [0.0, 1.00, 0.25,   0, 8, 'Overwrap_Ply_4']	
            
    Segment 1:
        CoreMaterial: 3
        Layup: 
            #-[Start[-],End[-],thickness[mm],Orientation [deg],MatID[int],'name'[str]]	
            - [0.0, 1.00, 3.0, 0, 2, 'Spar1']       
            
    Segment 2:
        CoreMaterial: 0
        Layup: 
            #Start[-],End[-],thickness[mm],Orientation [deg],MatID[int],name[str]	
            - [0.0, 1.0, 1.35, 0, 9, 'Spar_Cap_Ply_1']
            - [0.0, 1.0, 1.35, 45, 9, 'Spar_Cap_Ply_2']
            - [0.0, 1.0, 1.45, -45, 9, 'Spar_Cap_Ply_3']
            - [0.0, 1.0, 0.5, 90, 9, 'Spar_Cap_Ply_4']
            
    Segment 3:
        CoreMaterial: 11
        Layup: 
            #Start[-],End[-],thickness[mm],Orientation [deg],MatID[int],name[str]	
            - [0.96, 0.04, 3.1, 0,10, 'TE_Filler'] 

            
#=======BalanceWeight==	
BalanceWeight: 
    XPos: -116.5           	#	X Position	[-]						[float]				NO DEFAULT VALUE
    YPos: 1.0              	#	Y Position	[-]						[float]				NO DEFAULT VALUE
    Diameter: 14.0          	#	Diameter of Balance Weight [mm]		[float]				NO DEFAULT VALUE
    Material: 6             #   Material ID							[int]				NO DEFAULT VALUE
