#==============================SONATA-Configuration-Input YAML=============================
#This file contains the input information for the structural design of the rotorblade crosssection
#Author: Tobias Pflumm
#Date:	03/19/2018
#===============================SETUP===================================				 
Setup:
    input_type: 4						   #0) Airfoil from UIUC Database; 1) Geometry from .dat file; 2)2d .step 3)3D .step + radial station of crosssection 	4) gen, 3D-Blade f. twist,taper,airfoils,1/4-line	[int] DEFAULT=0	
    datasource: jobs/VariSpeed/uh60a_data_blade/uh60a_blade_zerotwist  #0)	naca23012					1) AREA_R250.dat			2)AREA_R230.stp	 			3)AREA_Blatt_L.stp	 4)folder of data 						                    [str] DEFAULT=NONE
    material_db: examples/mat_db.yml	   #Path and filename of the Material Database						#True or False for Balance Weight			                                                            [bool] DEFAULT=FALSE
    radial_station: 2000					#Radial station of crosssection. Only necessary for input type 3. [float]	Default=NONE
    Theta: 0							#To place the Origin of the SONATA Coordinates at the intersection of the by Theta rotated xaxis. [float] DEFAULT = 0
    scale_factor: 1						#use as reference scale factor				[float] 		DEFAULT=1
    BalanceWeight: False		
    mesh_resolution: 260				#Scales approximately to the number of points on Segment0


#=======WEBS=======			
Webs:
    Web 1:								#WebName									[int]	
        Pos1: 0.38						
        Pos2: 0.62

#=======SEGMENTS==	
Segments:
    Segment 0:							#Web ID 									[int]	
        CoreMaterial: 3
        Layup: 
            #-[Start[-],End[-],thickness[mm],Orientation [deg],MatID[int],'name'[str]]	
            - [0.00, 1.00, 1.20, 45, 1, 'Skin_1']
            - [0.00, 1.00, 1.20, 45, 1, 'Skin_2']

    Segment 1:							#Web ID 									[int]	
        CoreMaterial: 12
        Layup: 
            #-[Start[-],End[-],thickness[mm],Orientation [deg],MatID[int],'name'[str]]	
            - [0.00, 1.00, 2.20, 0, 2, 'Spar1']
            - [0.00, 1.00, 2.20, 0, 2, 'Spar2']
            - [0.00, 1.00, 2.20, 0, 2, 'Spar3']
            - [0.00, 1.00, 2.20, 0, 2, 'Spar4']
            
    Segment 2:							#Web ID 									[int]	
        CoreMaterial: 13
        Layup: 
            #-[Start[-],End[-],thickness[mm],Orientation [deg],MatID[int],'name'[str]]	

     
