#==============================SONATA-Configuration-Input YAML=============================
#This file contains the input information for the structural design of the rotorblade crosssection
#Author: Tobias Pflumm
#Date:	03/19/2018
#===============================SETUP===================================				 
Setup:
    input_type: 3						   #0) Airfoil from UIUC Database; 1) Geometry from .dat file; 2)2d .step 3)3D .step + radial station of crosssection 	4) gen, 3D-Blade f. twist,taper,airfoils,1/4-line	[int] DEFAULT=0	
    datasource: examples/AREA/AREA_Blatt_L.stp  #0)	naca23012					1) AREA_R250.dat			2)AREA_R230.stp	 			3)AREA_Blatt_L.stp	 4)folder of data 						                    [str] DEFAULT=NONE
    material_db: examples/mat_db.yml	   #Path and filename of the Material Database						#True or False for Balance Weight			                                                            [bool] DEFAULT=FALSE
    radial_station: 250					#Radial station of crosssection. Only necessary for input type 3. [float]	Default=NONE
    Theta: 6.4							#To place the Origin of the SONATA Coordinates at the intersection of the by Theta rotated xaxis. [float] DEFAULT = 0
    scale_factor: 1						#use as reference scale factor				[float] 		DEFAULT=1
    BalanceWeight: False		
    mesh_resolution: 280				#Scales approximately to the number of points on Segment0

#=======SEGMENTS==	
Segments:
    Segment 0:							#Web ID 									[int]	
        CoreMaterial: 3
        Layup: 
            #-[Start[-],End[-],thickness[mm],Orientation [deg],MatID[int],'name'[str]]	
            - [0.00, 1.00, 0.24, 45, 1, 'Skin_1']
            - [0.00, 1.00, 0.24, 45, 1, 'Skin_2']
            - [0.26, 0.74, 0.60, 45, 2, 'Spar_1']
            - [0.40, 0.61, 0.60, 45, 2, 'Spar_2']	
            - [0.41, 0.60, 0.60, 0, 2, 'Spar_3']
            - [0.42, 0.59, 0.60, 0, 2, 'Spar_4']
            - [0.31, 0.69, 0.60, 0, 2, 'Spar_5']
            - [0.18, 0.82, 0.60, 0, 2, 'Spar_6']
            - [0.41, 0.60, 0.24, 45, 1, 'Schubsteg_VK']
           # - [0.95, 0.05, 0.24, 45, 1, 'Schubsteg_HK']

