package:
  name: sonata
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

build:
  number: 2
  #number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ environ.get('GIT_BUILD_STR', '') }}

source:
  path: ..

requirements:
  build:
    - python >=3.6
  run:
    - python >=3.6
    - pythonocc-core >=7.4
    - openmdao >=2.8
    - pint
    - intervaltree
    - shapely

  imports:
    - SONATA

extra:
  recipe-maintainers:
    - tpflumm

  channels:
    - conda-forge
    - pythonocc

about:
  home: https://gitlab.lrz.de/gu32kij/SONATA
  license: LGPL
  summary: Multidiciplinary Rotor Blade Design Environment for Structural Optimization and Aeroelastic Analysis
  description: temporary description
