name: CI_windIO

# We run CI on push commits and pull requests on all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build (${{ matrix.os }} Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}

    defaults:
        run:
            shell: bash -l {0}


    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      # Official way to do miniconda, but it messes with the worker environment and shell
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        # https://github.com/marketplace/actions/setup-miniconda
        with:
          miniconda-version: "latest"
          channels: conda-forge
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yaml
          activate-environment: test
          auto-activate-base: false
          
      - name: Run examples
        run: |
          cd examples
          cd 0_beams
          python 0_SONATA_init_box_beam_HT_antisym_layup_(15)6_SI_SmithChopra91.py
